wondertrader/wondertrader

docker/Dockerfile, docs/install.md
=> 提供使用dockerfile来构建开发环境的选项。

src/WtBtCore/HftMocker.cpp
=> [debug] 内存泄漏处理

src/WtBtCore/HftMocker.cpp
仓位更新调整到on_trade之前，否则在on_trade中，无法获取到最新的仓位
=> 仓位更新调整到on_trade之前

src/WtExecMon/WtExecRunner.cpp
handleQuote 与 handle_push_quote中对代码进行了两次重复的解析，删除了handle_push_quote中多余的解析
=> [mod] 解决重复解析代码的bug

src/Includes/IHftStraCtx.h, src/WtBtCore/HftMocker.cpp, src/WtBtCore/HftMocker.h, src/WtCore/HftStraBaseCtx.cpp, src/WtCore/HftStraBaseCtx.h, src/WtCore/HftStraContext.cpp
[mod] 调整了hft 引擎中get_position的参数，允许获得多空的实际持仓
=> [mod] 调整hft持仓查询

src/ParserXTP/ParserXTP.cpp, src/TraderXTP/TraderXTP.cpp, src/TraderXTP/TraderXTP.h
=> [mod] Xtp相关调整

src/ParserHuaX/ParserHuaX.cpp
char*到char的转换有点问题，不能直接转换，虽然能够编译通过
=> [mod] 修复了一个char*转char的错误

src/WtBtCore/CtaMocker.cpp, src/WtBtCore/CtaMocker.h, src/WtBtPorter/WtBtRunner.cpp, src/WtBtPorter/WtBtRunner.h, src/WtBtRunner/WtBtRunner.cpp
增加增量回测接口，通过在config中添加`incremental_backtest_base: outputs_bt`配置实现：
```yaml
env:
mocker: cta                 #回测引擎，cta/sel/hft/exec/uft
incremental_backtest_base: outputs_bt/dt_if_0110
```
=> [mod] 增加增量回测模式

src/TraderAresClt/TraderAresClt.cpp, src/TraderMAOpt/TraderMAOpt.cpp, src/TraderMAOpt/TraderMAOpt.h, src/WtCore/WtDiffExecuter.cpp
[mod] 去除了maCliopt接口部分无效的日志打印
[fix] 修正了WtDiffExecuter类里diff初始化不成功的问题
=> [mod] 去除了qwin接口的部分无效日志打印，增加了断线重连成功后调用一次委托和成交查询

docker/Dockerfile
1.setup nanomsg in image
2.setup sudo cmd
3.update image to yagerfgcs/wondertrader:v0.1
4.make image process can see : https://blog.csdn.net/yagerfgcs/article/details/128887099\?spm\=1001.2014.3001.5502
=> update dockerfile to support mac linux developer 

src/WtDataStorage/WtDataReader.cpp
1 增加_rt_cursor过滤，避免重复读取rt数据
2 调整hisCnt与rtCnt的计算逻辑，正确显示读取情况
=> [mod] 修复readKlineSlice相关错误

src/WtBtCore/CtaMocker.cpp
在bar回测中，经常会出现同一个价格触发了多个条件单时，要选出一个作为最终的触发价，遵循以下规则：
1 alg不同的条件单，或者alg为WCT_Equal，以最先设置的那个为准
2 alg一样的调价单，如果是WCT_Larger与WCT_LargerOrEqual，取触发价较小的，WCT_Smaller与WCT_SmallerOrEqual，取触发价较大的
=> [mod] 调整分钟回测下的条件单的触发逻辑

src/WtExeFact/WtOrdMon.cpp, src/WtExeFact/WtOrdMon.h, src/WtExeFact/WtStockMinImpactExeUnit.cpp, src/WtExeFact/WtStockMinImpactExeUnit.h
=> [mod] 增加股票执行器

src/WtExeFact/WtTWapExeUnit.cpp, src/WtExeFact/WtTWapExeUnit.h
TwapUnintExe_add_1   by zhaoyk
=> TwapUnitExe_add_1

src/WtExeFact/WtExeFact.cpp
[Include vwapunitexe&&vwap.txt and update twapunitexe with exefact.]
=> 新增VWap单元withVwap.txt并更新TwapUnit和ExeFact

src/WtExeFact/WtExeFact.cpp, src/WtExeFact/WtExeFact.vcxproj, src/WtExeFact/WtExeFact.vcxproj.filters, src/WtExeFact/WtMinImpactExeUnit.cpp, src/WtExeFact/WtStockMinImpactExeUnit.cpp, src/WtExeFact/WtStockVWapExeUnit.cpp, src/WtExeFact/WtStockVWapExeUnit.h, src/WtExeFact/WtTWapExeUnit.cpp, src/WtExeFact/WtTWapExeUnit.h, src/WtExeFact/WtVWapExeUnit.cpp, src/WtExeFact/WtVWapExeUnit.h
Change twap/vwapUnit.Include stocksvwapUnit and change stocksminimpactUnit.
=> Change twap/vwapUnit.Include stocksvwapUnit and change stocksminimpactUnit

src/WTSUtils/StackTracer/StackTracer.cpp, src/WtBtCore/CtaMocker.cpp, src/WtDataStorage/WtDataWriter.h
通过 ./build_release.sh 修复构建
如果没有这些更改，该框架将无法在我的计算机上编译  (ubuntu 22.04)
另外，master也被合并到这个分支中
抱歉，如果我的中文不正确
=> 通过 ./build_release.sh 修复构建

src/WTSTools/CsvHelper.cpp
[修复csv最后一行可能存在\t导致读不出来的bug](https://github.com/wondertrader/wondertrader/commit/f9015ffafa282facfda25c86166c8f9891e650c1)
=> 修复csv最后一行可能存在\t导致读不出来的bug

src/Share/TimeUtils.hpp
检测 mktime() 是否成功应该在 UTC 转换之前
之前误操作了，抱歉：#213
对应 Issue: #210
=> [fix] TimeUtils::makeTime()

src/CTPLoader/TraderSpi.cpp
=> CTPLoader增加新品种日志输出

src/WtDataStorage/WtDataReader.cpp
=> [fix]修正WtDataReader::readKlineSlice读取盘中后复权数据时更新缓存个数出错的bug

src/Includes/WTSTypes.h
=> Update WTSTypes.h 关于两融部分的参数
